quarkus:
  
  http:
    port: 9090
    cors:
      enabled: true

  langchain4j:
    ollama:
      base-url: "http://localhost:11434"
      timeout: 120s
      chat-model:
        model-name: "qwen2.5:3b"
    
    mcp:
      borysmcp:
        transport-type: streamable-http
        url: "http://localhost:9100/mcp/v1"
        log-requests: true
        log-responses: true