services:
  # 1. Il motore principale di InfluxDB 3 Core (Scritto in Rust)
  influxdb3-core:
    image: influxdb:3-core
    container_name: influxdb3-core
    user: root # <--- RISOLVE IL PERMISSION DENIED
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0                  # Identificativo del nodo singolo
      - --object-store=file             # Indica di salvare i file parquet localmente
      - --data-dir=/influxdb3 create token --adminvar/lib/influxdb3/data
    volumes:
      - influxdb3_data:/var/lib/influxdb3/data
    restart: unless-stopped

  # 2. La nuova interfaccia web ufficiale (InfluxDB 3 Explorer)
  influxdb3-explorer:
    image: influxdata/influxdb3-ui:latest
    container_name: influxdb3-explorer
    ports:
      - "8080:8080"                     # Interfaccia grafica accessibile da browser
    environment:
      - SESSION_SECRET_KEY=XT5i7JGPSZmktefsUu4cjGwbA7DPZB
    command:
      - --mode=admin                    # Avvia l'interfaccia in modalità amministrativa
    volumes:
      - explorer_db:/db
    restart: unless-stopped
    depends_on:
      - influxdb3-core

volumes:
  influxdb3_data:
  explorer_db: